# Generated by Django 4.2.4 on 2023-09-27 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course_progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
