# Generated by Django 4.2.4 on 2023-09-15 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='quallification',
            new_name='qualification',
        ),
    ]
