# Generated by Django 4.2.4 on 2023-09-04 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_thumbnail_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category'),
        ),
    ]
