# Generated by Django 4.2.4 on 2023-10-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_forgotpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
